version: '3.9'

services:
  postgres_db:
    image: postgres:16
    hostname: postgres-db
    environment:
      POSTGRES_PASSWORD: "postgres1"
      POSTGRES_USER: "postgres1"
      POSTGRES_DB: "postgres1"
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U postgres1
      interval: 2s
      timeout: 3s
      retries: 40

  mysql_db:
    image: mysql:8.0
    hostname: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "mysql1"
      MYSQL_DATABASE: "mysql1"
      MYSQL_USER: "mysql1"
      MYSQL_PASSWORD: "mysql1"
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 10

volumes:
  postgres-db-data:
    name: postgres-db-data
  mysql-db-data:
    name: mysql-db-data
